platform :ios, '9.0'
inhibit_all_warnings!
use_frameworks!

target 'XYKit' do
    ## rac
    pod 'ReactiveObjC'
    ## 自定义导航栏
    pod 'RTRootNavigationController'
    ## 极光推送
    pod 'JPush', '~> 3.2.2'
    ## YYKit
    pod 'YYText'
    pod 'YYCategories'
    ## 约束
    pod 'Masonry'
    ## 网络请求
    pod 'PPNetworkHelper'
    ## 提示框
    pod 'MBProgressHUD'
    ## 空数据视图
    pod 'DZNEmptyDataSet'
    ## 加载网络图片
    pod 'SDWebImage'
    ## 解析后台数据
    pod 'MJExtension'
    ## 下拉刷新上拉加载
    pod 'MJRefresh'
    ## 跳转相册
    pod 'TZImagePickerController'
    ## 转场动画
    pod 'HHTransition'
    ## 自适应键盘高度
    pod 'IQKeyboardManager'
    ## 轮播图
    pod 'SDCycleScrollView'
    ## 数据库
    pod 'BGFMDB'
    ## 启动页广告
    pod 'XHLaunchAd', '~> 3.9.8'
    ## 友盟统计和分享
    pod 'UMengAnalytics', '~> 4.2.4'
    pod 'UMessage', '~> 1.4.0'
    ## U-Share SDK登录分享
    pod 'UMengUShare/UI'
    pod 'UMengUShare/Social/ReducedWeChat'
    pod 'UMengUShare/Social/QQ'
    pod 'UMengUShare/Social/Sina'
    ## 图片浏览器 视频播放器
    pod 'YBImageBrowser', '~> 3.0.1' #图片浏览
    pod 'YBImageBrowser/Video', '~> 3.0.1' #播放视频
    ## 动态监听/动态修复闪退
    pod 'JJException'
    ## 百度地图
    pod 'BaiduMapKit', '~> 4.4.2' #百度地图
    pod 'BMKLocationKit', '~> 1.7.0' #百度定位
    ## tabBar自定义动画
    pod 'TLAnimationTabBar'
    ## 超强charts图表
    pod 'AAChartKit'
    ## 导航栏多段控制器
    pod 'SGPagingView'
    
    ## 调试工具（App发版时记得移除该库）
    pod 'FLEX'
end
